spring:
  application:
    name: UberServiceDiscovery

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # Server doesn't register itself
    fetch-registry: false # It's the registry, not a client
